# Generated by Django 2.2.14 on 2020-08-05 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20200803_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='root_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'In-stock'), ('p', 'Pending-shipment'), ('o', 'Out-of-stock')], default='i', help_text='Stock availability', max_length=1),
        ),
    ]
