# Generated by Django 2.2.14 on 2020-08-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200805_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='root_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product'),
        ),
    ]
