# Generated by Django 2.2.14 on 2020-08-07 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200807_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_edited',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 7, 15, 22, 53, 277818)),
            preserve_default=False,
        ),
    ]
