# Generated by Django 2.2.14 on 2020-08-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_tag',
            field=models.CharField(default='tag', max_length=50),
            preserve_default=False,
        ),
    ]
